// react-star-app/src/App.js
import React, { useEffect, useState } from 'react';
import logo from './logo.svg';
import './App.css';

function App() {

  function addEventListenerForStar() {
    const starRating = starRatingRef.current;
    if (!starRating) {
      return;
    }
    starRating.addEventListener('rated', (e) => {
      const { itemClicked } = e.detail;
      setItemClicked(itemClicked + 1);
    })
  }

  const [maxStar, setMaxStar] = useState(10);
  const [itemClicked, setItemClicked] = useState(0);
  const starRatingRef = React.createRef();

  useEffect(() => {
    addEventListenerForStar();
  });

  return (
    <div className="App">
      Hello This is react App
      <star-rating ref={ starRatingRef } max={ maxStar }></star-rating>
      <h5>You clicked on { itemClicked }</h5>
      <button onClick={ setMaxStar.bind(this, [20]) }>Set to 20</button>
    </div>
  );
}

export default App;

// ng-star/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent implements AfterViewInit {
  title = 'This is Angular project using star';
  itemClicked = 0;
  amountStar = 4;

  @ViewChild('starRating', { read: ElementRef, static: false })
  public starRating;

  public onRating({ detail }) {
    this.itemClicked = detail.itemClicked + 1;
  }

  public setRatingAmount(numRatings): void {
    this.amountStar = numRatings;
  }

  public ngAfterViewInit(): void {
  }
}

<h3>{{ title }}</h3>


<star-rating #starRating [attr.max]="amountStar" (rated)="onRating($event)"></star-rating>


<h4>You clicked on {{ itemClicked }}</h4>


<button (click)="setRatingAmount(10)">Set Amount of Star to 10</button>
